In [2]:
import numpy as np

In [3]:
#integer array
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
#integer float
arr = np.array([1.,2,3,4,5])

In [6]:
arr

array([1., 2., 3., 4., 5.])

In [7]:
arr.dtype

dtype('float64')

In [8]:
print(arr)

[1. 2. 3. 4. 5.]


In [16]:
arr.shape

(5,)

In [17]:
arr.nbytes

40

In [18]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0],[5.0,4.0]])
print(matrix)

[list([9.0, 8.0, 7.0]) list([6.0, 5.0]) list([5.0, 4.0])]


In [14]:
matrix.ndim

1

In [19]:
arr.size

5

In [20]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [21]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr.shape

(3, 4)

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [26]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [27]:
# uniform distribution
np.random.rand(5,2)

array([[0.41096455, 0.19635333],
       [0.28990753, 0.73903368],
       [0.64267291, 0.91137367],
       [0.32420804, 0.57314417],
       [0.77492812, 0.56237169]])

In [28]:
# normal distribution
np.random.randn(5,2)

array([[-0.47580926, -0.32588246],
       [ 1.17116878,  0.79553368],
       [-1.44506331,  0.42711236],
       [-0.69274221,  0.44863169],
       [-0.19492961,  0.96720216]])

In [29]:
np.random.randint(1,10, size=(3,3))

array([[2, 7, 4],
       [6, 9, 1],
       [4, 7, 8]])

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr = np.array([1,2,3,4,5,6])

In [39]:
arr[:-1]

array([1, 2, 3, 4, 5])

In [51]:
arr = np.array([[1, 2, 3, 4,5,4], [5, 6, 7, 8,6,7], [9, 10, 11, 12,13,15]])

In [52]:
print(arr)

[[ 1  2  3  4  5  4]
 [ 5  6  7  8  6  7]
 [ 9 10 11 12 13 15]]


In [42]:
arr[1,2]

7

In [45]:
arr[:,2]

array([ 3,  7, 11])

In [54]:
# arrayname[row,col]
# arrayname[start:end:stepsize]

In [53]:
arr[0,1:-1:2]

array([2, 4])

In [55]:
arr[1,2] = 20

In [56]:
print(arr)

[[ 1  2  3  4  5  4]
 [ 5  6 20  8  6  7]
 [ 9 10 11 12 13 15]]


In [57]:
sortedarray = np.arange(0,10)

In [58]:
sortedarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
sortedarray = np.arange(0,1000,3)

In [64]:
sortedarray

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231,
       234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270,
       273, 276, 279, 282, 285, 288, 291, 294, 297, 300, 303, 306, 309,
       312, 315, 318, 321, 324, 327, 330, 333, 336, 339, 342, 345, 348,
       351, 354, 357, 360, 363, 366, 369, 372, 375, 378, 381, 384, 387,
       390, 393, 396, 399, 402, 405, 408, 411, 414, 417, 420, 423, 426,
       429, 432, 435, 438, 441, 444, 447, 450, 453, 456, 459, 462, 465,
       468, 471, 474, 477, 480, 483, 486, 489, 492, 495, 498, 501, 504,
       507, 510, 513, 516, 519, 522, 525, 528, 531, 534, 537, 54

In [66]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
arr = np.array([1,2,3,4,5,6,45,67,89])

In [68]:
arr.max()

89

In [69]:
arr.min()

1

In [70]:
arr.argmax()

8

In [71]:
arr.argmin()

0

In [72]:
a = arr.copy()

In [73]:
a

array([ 1,  2,  3,  4,  5,  6, 45, 67, 89])