In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
# (it is not a method instead attribute)
arr.shape 

(10,)

In [4]:
arr.size

10

In [8]:
# reshape (row,col)
arr.reshape((3,3)) # error

ValueError: cannot reshape array of size 10 into shape (3,3)

In [9]:
arr.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
lst = [1,2,3,4,5,6]

In [11]:
lsttoarr = np.array(lst)

In [12]:
lsttoarr

array([1, 2, 3, 4, 5, 6])

In [13]:
a = np.array([1,2,3,4,5])

In [14]:
a + 2

array([3, 4, 5, 6, 7])

In [15]:
a - 2

array([-1,  0,  1,  2,  3])

In [16]:
a * 2

array([ 2,  4,  6,  8, 10])

In [17]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [18]:
b = np.array([1,0,1,0,1])

In [19]:
a + b

array([2, 2, 4, 4, 6])

In [23]:
a ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [24]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [25]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [26]:
np.tanh(a)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [27]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [28]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [29]:
i = np.identity(3)

In [30]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.linalg.det(i)

1.0

In [32]:
# https://numpy.org/doc/stable/reference/routines.linalg.html

In [33]:
stats = np.array([[1,2,3],[4,5,6]])

In [34]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.min(stats)

1

In [36]:
np.max(stats)

6

In [40]:
np.min(stats,axis =1)

array([1, 4])

In [41]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [42]:
np.std(stats)

1.707825127659933

In [43]:
np.var(stats)

2.9166666666666665

In [44]:
file = np.genfromtxt('data.txt',delimiter=',')

In [46]:
file = file.astype('int16')

In [47]:
file 

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int16)

In [48]:
# evenly spaced elemets within the given range
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [49]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [50]:
# most important concept of deep learning 

In [51]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

In [52]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [53]:
arr = np.array([16,25,36,64])

In [54]:
np.sqrt(arr)

array([4., 5., 6., 8.])

In [55]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [56]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])